### ISSUE TITLE
JdeRobot logo in the GUI of all the academic applications

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/Academy#110]
Let's put the logo of our project (the four colored circles) in the GUI of all the academic applications. Let's start with: 
- [x]  	3d_reconstruction
- [ ] 	bump_and_go 	
- [x]	color_filter 	
- [x]	drone_cat_mouse 	
- [x]	follow_line 	
- [x]	follow_road 	
- [x]	follow_turtlebot 	
- [x]	global_navigation 	
- [x]	labyrinth_escape 	
- [x]	obstacle_avoidance 	
- [x]	position_control 	
- [x]	rescue_people 	
- [ ]	visual_lander

**Comment by aitormf** [comment]
first approach in follow_line, creating a widget:

![captura de pantalla de 2017-01-02 14-06-00](https://cloud.githubusercontent.com/assets/16046048/21589709/e8998df6-d0f4-11e6-91bb-72efa6d8cd47.png)

**Comment by jmplaza** [comment]
Great Aitor
