### ISSUE TITLE
New exercise: Vacuum cleaner

### ISSUE THREAD

**Issue by vmartinezf** [JdeRobot/Academy#128]
The objective of this practice is that a robotic vacuum cleaner is able to autonomously clean as much surface area as possible in a house. This vacuum cleaner has a laser sensor, which allows you to measure the distance to which the obstacles are located.

In the graphical interface it is possible to visualize a map of the house, as well as the position of the vacuum cleaner on the map and the places where it has passed. The automatic evaluator will rate the practice according to some parameters.

**Comment by aitormf** [comment]
merged
